// Geteilte Icon-Map für Service-Cards & Feature-Cards (Homepage + /leistungen).
import {
  Palette,
  Smartphone,
  Zap,
  Search,
  MessageCircle,
  ShieldCheck,
  Rocket,
  Gauge,
  Layers,
  Repeat,
  LineChart,
  Users,
  Code2,
  Database,
  LayoutDashboard,
  Plug,
  Bell,
  RefreshCw,
  Star,
  Boxes,
  Workflow,
  FileText,
  Clock,
  Globe,
  Scissors,
  UtensilsCrossed,
  Wrench,
  Briefcase,
  type LucideIcon,
} from "lucide-react";

export const SERVICE_ICONS: Record<string, LucideIcon> = {
  palette: Palette,
  smartphone: Smartphone,
  zap: Zap,
  search: Search,
  message: MessageCircle,
  shield: ShieldCheck,
  rocket: Rocket,
  gauge: Gauge,
  layers: Layers,
  repeat: Repeat,
  chart: LineChart,
  users: Users,
  code: Code2,
  database: Database,
  dashboard: LayoutDashboard,
  plug: Plug,
  bell: Bell,
  refresh: RefreshCw,
  star: Star,
  boxes: Boxes,
  workflow: Workflow,
  file: FileText,
  clock: Clock,
  globe: Globe,
  scissors: Scissors,
  utensils: UtensilsCrossed,
  wrench: Wrench,
  briefcase: Briefcase,
};

export const FALLBACK_ICON: LucideIcon = Code2;
